Improve validator identifier processing
TobiWo/eth-duties pull request #25
Opened 2023-02-02 06:54 UTC by TobiWo

## Summary
This PR adds/fixes:
* You can now provide public keys for validators
* You can decide whether logging messages should use the validator index or pubkey - new cli flag `--log-pubkeys`
* Filters provided validators for inactive ones
  * fixes a bug where inactive or not present validators would cause `eth-duties` to not read any data

### Further changes
Furthermore this PR adds the foundation to get rid of the restriction that a user can only provide 300 validators for fetching attestation and sync committee duties. This will be fixed in another PR finally.

2023-02-03 05:29 UTC, LuisNaldo7 requested changes
I am unable to run with multiple indices provided. Providing `--validators "123456, 456789"` will lead to: "Couldn't read from beacon client. Retry in 5 seconds."
Either this is a bug or the documentation is outdated.

Furthermore starting with a single inactive index like `--validators "99999999"` the tool will filter it, print "...99999999 skipped..." and continue logging "Logging next interval... No upcoming duties detected!". A hint that there is no index being monitored would be great.

2023-02-27 20:06 UTC, LuisNaldo7 requested changes

2023-02-27 20:06 UTC, LuisNaldo7 commented on docker/compose.yaml
> +    image: "tobiwo/eth-duties:v0.3.0"
replace 'image' with

build:
      dockerfile: ./docker/dockerfile
      context: ../

this avoids the need to update the tag every time there is a new release

2023-02-27 20:06 UTC, LuisNaldo7 commented on duties/fetcher/parser/validators.py
> +    """Filters for duplicated validators which where provided with different identifiers
typp: where -> were

2023-03-01 14:13 UTC, TobiWo commented on docker/compose.yaml
> +name: "Compose for eth-duties helper tool"
Please check if your compose plugin or docker-compose binary is up to date. It works for me.

2023-03-01 14:14 UTC, TobiWo commented on README.md
> +    docker run --rm --name eth-duties tobiwo/eth-duties:latest --validators 123456 456789 --validators 0x98... --beacon-node http://locahost:5052
I changed several commands as your suggestion is true for all longer commands. Thanks

2023-03-01 18:45 UTC, LuisNaldo7 approved these changes

2023-03-02 07:07 UTC, LuisNaldo7 approved these changes

2023-03-02 14:09 UTC, merged